version: "3.7"
services:
  web:
    command: npm run dev
    container_name: next-docker-development
    # Set environment variables directly in the docker-compose file
    environment:
      NODE_ENV: development
      # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env    
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next