version: "3.7"
services:
  web:
    command: npm run production
    container_name: next-docker-production
    # Set environment variables directly in the docker-compose file
    environment:
      NODE_ENV: production
      # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env.prod   
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next